### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesingleconfigurationalstatesinglesiteoccupation
name: PrepareSingleConfigurationalStateSingleSiteOccupation
type: operation
namespace: microsoft.quantum.chemistry.jordanwigner
summary: Semplice preparazione dello stato della versione di valutazione mediante l'inclusione degli orbitali
syntax: 'operation PrepareSingleConfigurationalStateSingleSiteOccupation (qubitIndices : Int[], qubits : Qubit[]) : Unit'
input:
  content: '(qubitIndices : Int[], qubits : Qubit[])'
  types:
  - name: qubitIndices
    summary: Indici di qubits che devono essere occupati da elettroni.
    isArray: true
    isPrimitive: true
    uid: Int
  - name: qubits
    summary: Qubits di hamiltoniana.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
functors:
- Adjoint
- Controlled
metadata:
  ms.openlocfilehash: 6ae72c826058288ba2318b0056cf017e571e216e
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89339389"
