### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Summary\n Queste funzioni forniscono informazioni sull'ambiente in cui si verifica il calcolo quantistico."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Restituisce il numero di qubits attualmente disponibili per il prestito.

    Sono inclusi i qubits inutilizzati; Ciò è incluso il qubits restituito da `GetQubitsAvailableToUse`.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Restituisce il numero di qubits attualmente disponibili per l'utilizzo.
metadata:
  ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73056821"
