### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Restituisce il numero di qubits attualmente disponibili per il prestito.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Restituisce il numero di qubits attualmente disponibili per l'utilizzo.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Queste funzioni forniscono informazioni sull'ambiente in cui si verifica il calcolo quantistico.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201445"
