### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Restituisce il numero di qubits attualmente disponibili per l'utilizzo.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Numero di qubits che possono essere allocati in un' `using` istruzione.

      Se il computer di destinazione utilizzato non fornisce queste informazioni, `-1` viene restituito.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 82d8c27064cbb234b32707aa31fb0869f66ce23c
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682389"
