### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Restituisce il numero di qubits attualmente disponibili per il prestito.

  Sono inclusi i qubits inutilizzati; Ciò è incluso il qubits restituito da `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Numero di qubits che possono essere allocati in un' `borrowing` istruzione.

      Se il computer di destinazione utilizzato non fornisce queste informazioni, `-1` viene restituito.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 99dd2afb66c334b112a2ee511b0437281da6b888
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682419"
