### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Restituisce il numero di qubits attualmente disponibili per il prestito. Sono inclusi i qubits inutilizzati; Ciò è incluso il qubits restituito da `GetQubitsAvailableToUse` .
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Restituisce il numero di qubits attualmente disponibili per l'utilizzo.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Queste funzioni forniscono informazioni sull'ambiente in cui si verifica il calcolo quantistico.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 04a3ffe56be7da2c9adc13e2b27fe9ce0f982c44
  ms.sourcegitcommit: 29e0d88a30e4166fa580132124b0eb57e1f0e986
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 10/27/2020
  ms.locfileid: "92713180"
