### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Restituisce il numero di qubits attualmente disponibili per il prestito.

  Sono inclusi i qubits inutilizzati; Ciò è incluso il qubits restituito da `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Numero di qubits che possono essere allocati in un'istruzione `borrowing`.

      Se il computer di destinazione utilizzato non fornisce queste informazioni, viene restituito `-1`.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73230484"
