### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: microsoft.quantum.environment
summary: Restituisce il numero di qubits attualmente disponibili per l'utilizzo.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Numero di qubits che possono essere allocati in un' `using` istruzione.

      Se il computer di destinazione utilizzato non fornisce queste informazioni, `-1` viene restituito.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 326195ba3fa7b880d9b6871d16ea7a12c1c9a2ea
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91484734"
