### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesingleconfigurationalstatesinglesiteoccupation
name: PrepareSingleConfigurationalStateSingleSiteOccupation
type: operation
namespace: microsoft.quantum.chemistry.jordanwigner
summary: Semplice preparazione dello stato della versione di valutazione mediante l'inclusione degli orbitali
syntax: 'operation PrepareSingleConfigurationalStateSingleSiteOccupation (qubitIndices : Int[], qubits : Qubit[]) : Unit'
input:
  content: '(qubitIndices : Int[], qubits : Qubit[])'
  types:
  - name: qubitIndices
    summary: Indici di qubits che devono essere occupati da elettroni.
    isArray: true
    isPrimitive: true
    uid: Int
  - name: qubits
    summary: Qubits di hamiltoniana.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
functors:
- Adjoint
- Controlled
metadata:
  ms.openlocfilehash: adf59a551e855fbc7b4b9e0ca319a2178ab4ffa1
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91479940"
